import React, { useState } from "react";
import Book from "./Book";
function BookList() {
  const [books, setBooks] = useState([
    {
      title: "The Lord Of The Rings",
      author: "J R Tolkien"
    },
    {
      title: "The Hobbit",
      author: "J R Tolkien"
    }
  ]);

  function addBook(book) {
    // Code Generated by Sidekick is for learning and experimentation purposes only.
    setBooks([...books, book]);
  }
  return (
      <div className="table-responsive">
     
     <button type="button" className="btn btn-primary" 
          onClick={() => {
              addBook({ title: "The Silmarillion", 
        author: "J R R Tolkien" });
      }}>Add Book</button>

        <table className="table table-bordered table-striped">
          <thead>
            <tr>
                <th>Book</th>
                <th>Author</th>
            </tr>
          </thead>
          <tbody>
          {books.map((book, idx) => (
            <Book key={idx} title={book.title} author={book.author}  />
          ))}
        </tbody>

        </table>


      </div>
    );
  }

  export default BookList;
